// <auto-generated />
using System;
using EletroGestao.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EletroGestao.Infra.Data.Migrations
{
    [DbContext(typeof(EletroGestaoContext))]
    [Migration("20231205164056_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("EletroGestao.Dominio.ClienteRoot.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("varchar(14)")
                        .HasColumnName("documento");

                    b.Property<string>("NomeRazaoSocial")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nomeRazaoSocial");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("EletroGestao.Dominio.PedidoRoot.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CEP");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime")
                        .HasColumnName("data");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("datetime")
                        .HasColumnName("dataEntrega");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("char(36)")
                        .HasColumnName("IdCliente");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("char(36)")
                        .HasColumnName("IdProduto");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nomeCliente");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nomeProduto");

                    b.Property<string>("NumeroPedido")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("numeroPedido");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("regiao");

                    b.Property<decimal>("ValorFinal")
                        .HasColumnType("decimal(15,5)")
                        .HasColumnName("valorFinal");

                    b.Property<decimal>("ValorFrete")
                        .HasColumnType("decimal(15,5)")
                        .HasColumnName("valorFrete");

                    b.Property<decimal>("ValorProduto")
                        .HasColumnType("decimal(15,5)")
                        .HasColumnName("valorProduto");

                    b.HasKey("Id");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("EletroGestao.Dominio.ProdutoRoot.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nomeProduto");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(15,5)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.ToTable("Produtos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
